config/routes.rb
Rails.application.routes.draw do
  get 'grams/custom' => 'grams#custom' , as:'hihi'
  resources :grams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # shortcut for : and all 7 routes
  # get '/grams' => 'grams#index
  # if don't want all 7 routes can specify indifidually
  resources :users


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gram.rb
class Gram < ApplicationRecord
  validates_presence_of :title, :content, :location
end
#models are singular - gram

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :name, :email, :age
  validates_uniqueness_of :email, case_sensitive: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :set_gram, only: [:show, :edit, :update, :destroy]

  # GET /grams
  # GET /grams.json
  def index
    @grams =
      if current_user
        current_user.grams.page(params[:page]).per(2)
      else
        Gram.page(params[:page]).per(2)
      end
  end

  # GET /grams/1
  # GET /grams/1.json
  def show
  end

  # GET /grams/new
  def new
    unless current_user
      flash[:error] = "You need to log in before creating a new gram."
      redirect_to grams_path
    end

    @gram = Gram.new
  end

  # GET /grams/1/edit
  def edit
  end

  # POST /grams
  # POST /grams.json
  def create
    @current_user = current_user

    # user1 = Users.find(1)
    # user1.grams (all grams that belong to the user)
    # user1.grams.create -> will have user_id set to user1

    @gram = @current_user.grams.new(gram_params)

    respond_to do |format|
      if @gram.save
        format.html { redirect_to @gram, notice: 'Gram was successfully created.' }
        format.json { render :show, status: :created, location: @gram }
      else
        format.html { render :new }
        format.json { render json: @gram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grams/1
  # PATCH/PUT /grams/1.json
  def update
    respond_to do |format|
      if @gram.update(gram_params)
        format.html { redirect_to @gram, notice: 'Gram was successfully updated.' }
        format.json { render :show, status: :ok, location: @gram }
      else
        format.html { render :edit }
        format.json { render json: @gram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grams/1
  # DELETE /grams/1.json
  def destroy
    @gram.destroy
    respond_to do |format|
      format.html { redirect_to grams_url, notice: 'Gram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def custom

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gram
      @gram = Gram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gram_params
      # params.fetch(:gram, {})
      params.require(:gram).permit(:title, :content, :location, :country_code, :image_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def edit

  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user}
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #params.fetch(:gram, {})
      params.require(:user).permit(:name, :email, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def country_name(country_code)
    return "No country code provided" if country_code.nil?
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s]
  end
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/grams/_form.html.erb
<%= form_with(model: gram, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title , class: 'form-control', placeholder: "Title"%>
  </div>
  <div class="form-group">
    <%= form.label :content%>
    <%= form.text_area :content, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= form.label :location%>
    <%= form.text_field :location, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= form.label :country_code%>
    <%= form.country_select :country_code, {include_blank: true, priority_countries: ["SG", "MY"]}, {class: 'form-control'}%>
  </div>

  <div>
    <%= form.hidden_field :image_url, role: 'uploadcare-uploader', data: {crop: '600:600', 'images-only' => true} %>
  </div>

  <% if gram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gram.errors.count, "error") %> prohibited this gram from being saved:</h2>

      <ul>
      <% gram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/grams/_mypartial.html.erb
<%= form_with do |form| %>

<h1>Hi!</h1>
<p> This is my partial.</p>

<% end %>

app/views/grams/custom.html.erb
<h1>custom Method</h1>

<%= link_to 'Back', grams_path %>

app/views/grams/edit.html.erb
<h1>Editing Gram</h1>

<%= render 'form', gram: @gram %>

<%= link_to 'Show', @gram %> |
<%= link_to 'Back', grams_path %>

app/views/grams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grams</h1>

<!-- <table class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Location</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @grams.each do |gram| %>
      <tr>
        <td><%= gram.title %></td>
        <td><%= gram.content %></td>
        <td><%= gram.location %></td>
        <td><%= country_name(gram.country_code) %></td>
        <td><%= image_tag gram.image_url unless gram.image_url.nil? %></td>
        <td><%= link_to 'Show', gram %></td>
        <td><%= link_to 'Edit', edit_gram_path(gram) %></td>
        <td><%= link_to 'Destroy', gram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<div class="row">
  <div class="col-xs-1 col-md-1">Title</div>
  <div class="col-xs-1 col-md-1">Content</div>
  <div class="col-xs-1 col-md-1">Location</div>
  <div class="col-xs-1 col-md-1">Country Code</div>
  <div class="col-xs-1 col-md-5">Image</div>
  <div class="col-xs-1 col-md-1">Show</div>
  <div class="col-xs-1 col-md-1">Edit</div>
  <div class="col-xs-1 col-md-1">Destroy</div>
</div>

<% @grams.each do |gram| %>
  <div class="row">
    <div class="col-md-1"><%= gram.title %></div>
    <div class="col-md-1"><%= gram.content %></div>
    <div class="col-md-1"><%= gram.location %></div>
    <div class="col-md-1"><%= country_name(gram.country_code) %></div>
    <div class="col-md-5"><%= image_tag gram.image_url, class: "img-responsive" unless gram.image_url.nil? %></div>
    <div class="col-md-1"><%= link_to 'Show', gram, class: "btn btn-primary"%></div>
    <div class="col-md-1"><%= link_to 'Edit', edit_gram_path(gram), class: 'btn btn-warning' %></div>
    <div class="col-md-1"><%= link_to 'Destroy', gram, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></div>
  </div>
<% end %>

<br>
<div class="text-center">
  <%= paginate @grams %>
</div>
<br>

<%= link_to 'New Gram', new_gram_path, class: "btn btn-primary" if current_user %>

app/views/grams/new.html.erb
<h1>New Gram</h1>

<%= render 'form', gram: @gram %> <!-- this renders a partial-->

<%= link_to 'Back', grams_path %>

app/views/grams/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
   <div class='col-sm-6 col-sm-offset-3'>
     <div class='panel panel-default'>
       <div class='panel-heading'>
         <div class='row'>
           <div class='col-sm-6'>
             Me
           </div>
           <div class='col-sm-6 text-right'>
             <span class='created_at'><%= link_to time_ago_in_words(@gram.created_at), gram_path(@gram) %></span>
             &nbsp;
             <%= link_to icon('trash-o'), gram_path(@gram), method: :delete, data: { confirm: 'Are you sure you want to delete this Gram?'} %>
           </div>
         </div>
       </div>
       <div class='panel-body'>
         <div><%= image_tag @gram.image_url unless @gram.image_url.nil?%></div>
       </div>
       <div class='panel-footer'>
         <div class='gram-title'><%= @gram.title %></div>
         <div class='gram-location'><%= icon('map-marker') %> <%= country_name(@gram.country_code) %></div>
         <div class='gram-content'><%= @gram.content %></div>
       </div>
    </div>
  </div>
</div>

<div class="text-center">
<%= link_to 'Edit', edit_gram_path(@gram), class: "btn btn-warning"%> |
<%= link_to 'Back', grams_path, class: "btn btn-primary"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minigram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      UPLOADCARE_PUBLIC_KEY = "6fe1559648b0a3c53dce";
    </script>
    <script charset="utf-8" src="//ucarecdn.com/libs/widget/3.1.1/uploadcare.full.min.js"></script>
  </head>

  <body class='container'>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name%>
  <%= form.label :email%>
  <%= form.text_field :email%>
  <%= form.label :age%>
  <%= form.number_field :age%>

  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gram.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %> <!-- logic erb -->
      <tr>
        <td><%= user.name%></td> <!--erb, embedded ruby indexes, will evaluate the codes -->
        <td><%= user.email%></td> <!-- evaluate into something -->
        <td><%= user.age%></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %> <!-- this renders a partial-->

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>Name: <%= @user.name%></p>
<p>Email: <%= @user.email%></p>
<p>Age: <%= @user.age%></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>